# Generated by Django 3.2.8 on 2022-11-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=40)),
                ('Appointment_date', models.DateField()),
                ('Appointment_start_time', models.TimeField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
