# Generated by Django 3.2.8 on 2022-11-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentschedule',
            name='Appointment_date',
            field=models.DateTimeField(),
        ),
    ]
