# Generated by Django 3.2.8 on 2022-11-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_appointmentschedule_appointment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RenameField(
            model_name='appointmentschedule',
            old_name='Appointment_date',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='appointmentschedule',
            old_name='patient_name',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='appointmentschedule',
            name='Appointment_start_time',
        ),
    ]
