# Generated by Django 4.0.1 on 2022-02-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregisteration',
            name='adhar_card',
            field=models.CharField(max_length=12),
        ),
    ]
